FROM python:latest

RUN apt -y install git

RUN apt update -y

RUN apt upgrade -y

RUN apt -y install python3-pip

RUN git clone https://github.com/kura-labs-org/kuralabs_deployment_3.git

WORKDIR /kuralabs_deployment_3

RUN pip install -r requirements.txt

RUN pip install gunicorn

EXPOSE 5000

ENTRYPOINT FLASK_APP=app flask run -p 5000 &
